services:
  - type: web
    name: thronixpro-ai
    env: python
    buildCommand: "pip install -r requirements.txt && python init_db.py"
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false